### ISSUE TITLE
System.ArgumentException: Value does not fall within the expected range.

### ISSUE THREAD

**Issue by SunTea07** [Leanny/PKHeX_Raid_Plugin#25]
I've tried the latest version of the plugin + pkhex and this error shows up when i load display raids don't know if this is an issue or not

EDIT:

this error shows up on display raids

![image](https://user-images.githubusercontent.com/16289227/73590961-d0f35000-4523-11ea-9fc0-f476a17a1066.png)

and yes the plugin is already unblocked 

![image](https://user-images.githubusercontent.com/16289227/73590977-f54f2c80-4523-11ea-92ab-a812cddf14b4.png)

Error Message:

Exception Details:
System.ArgumentException: Value does not fall within the expected range.
   at PKHeX_Raid_Plugin.EventTableConverter.GetCurrentEventTable(SaveBlockAccessor8SWSH blocks, RaidTables rt)
   at PKHeX_Raid_Plugin.RaidManager..ctor(SaveBlockAccessor8SWSH blocks, GameVersion game, Int32 badges, UInt32 tid, UInt32 sid)
   at PKHeX_Raid_Plugin.RaidList..ctor(SaveBlockAccessor8SWSH blocks, GameVersion game, Int32 badges, Int32 tid, Int32 sid)
   at PKHeX_Raid_Plugin.RaidPlugin.Open()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

PKHeX, Version=20.1.26.0, Culture=neutral, PublicKeyToken=null
C:\Pkhex\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

PKHeX_Raid_Plugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Pkhex\plugins\PKHeX_Raid_Plugin.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

**Comment by Leanny** [comment]
Can you send me your savegame so I can reproduce the issue?

**Comment by SunTea07** [comment]
[Savefile.zip](https://github.com/Leanny/PKHeX_Raid_Plugin/files/4142452/Savefile.zip)

**Comment by Leanny** [comment]
Should be fixed now. I made a new release
