### ISSUE TITLE
Worked once and then i got this error when i closed and reopened.

### ISSUE THREAD

**Issue by acecustis** [Leanny/PKHeX_Raid_Plugin#31]
So, it worked once, and then when i try to display raids it shows me this message.

Exception Details:
System.MissingMethodException: Method not found: 'Byte PKHeX.Core.RaidSpawnDetail.get_DenType()'.
   at PKHeX_Raid_Plugin.RaidParameters..ctor(Int32 index, RaidSpawnDetail detail, Int32 location, Int32 x, Int32 y)
   at PKHeX_Raid_Plugin.RaidManager.InitializeDenList(RaidSpawnList8 raids)
   at PKHeX_Raid_Plugin.RaidManager..ctor(SaveBlockAccessor8SWSH blocks, GameVersion game, Int32 badges, UInt32 tid, UInt32 sid)
   at PKHeX_Raid_Plugin.RaidList..ctor(SaveBlockAccessor8SWSH blocks, GameVersion game, Int32 badges, Int32 tid, Int32 sid)
   at PKHeX_Raid_Plugin.RaidPlugin.Open()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

PKHeX, Version=20.2.8.0, Culture=neutral, PublicKeyToken=null
C:\Users\ace\Desktop\Poker hack chekar seeds\PKHeX (191226)\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

System.Windows.Forms.resources, Version=4.0.0.0, Culture=es, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms.resources\v4.0_4.0.0.0_es_b77a5c561934e089\System.Windows.Forms.resources.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

PKHeX_Raid_Plugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\ace\Desktop\Poker hack chekar seeds\PKHeX (191226)\plugins\PKHeX_Raid_Plugin.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\ace\Desktop\Poker hack chekar seeds\PKHeX (191226)\plugins\PKHeX_Raid_Plugin\deps\PKHeX.Drawing.dll

mscorlib.resources, Version=4.0.0.0, Culture=es, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_es_b77a5c561934e089\mscorlib.resources.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

**Comment by Leanny** [comment]
Do you use the latest version of PKHeX and the Plugin? It looks like one of them is not the latest version

**Comment by acecustis** [comment]
Thank you, i deleted everything and installed all lastest versions and it worked thanks.!
