### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by brianomatic** [Leanny/PKHeX_Raid_Plugin#38]
I installed the DLL to the plugin folder and unblocked it as well as put the 2 required windows 64bit DLL in the same folder as pkhex and I get the following error:

Exception Details:
System.BadImageFormatException: Could not load file or assembly 'file:///C:\Users\Brian\Desktop\Pokemon Editor\plugins\z3-4.8.7-x64-win\bin\libz3.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'file:///C:\Users\Brian\Desktop\Pokemon Editor\plugins\z3-4.8.7-x64-win\bin\libz3.dll'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at PKHeX.WinForms.Main.FormLoadPlugins()
   at PKHeX.WinForms.Main..ctor()
   at PKHeX.WinForms.Program.Main()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

PKHeX, Version=20.3.14.0, Culture=neutral, PublicKeyToken=null
C:\Users\Brian\Desktop\Pokemon Editor\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

AutoModPlugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Brian\Desktop\Pokemon Editor\plugins\AutoModPlugins.dll

PKHeX_Raid_Plugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Brian\Desktop\Pokemon Editor\plugins\PKHeX_Raid_Plugin.dll

QRPlugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Brian\Desktop\Pokemon Editor\plugins\QRPlugins.dll

PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
C:\Windows\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll

WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll

--------------------
User Message:
An unhandled exception has occurred.
PKHeX must now close.

**Comment by brianomatic** [comment]
Never mind, i'm an idiot. Cancel and thank you for your work... 

Note to other users: if you download and extract the z3-4.8.7-XXX files in the plugin folder then move them to the root folder you will get this error... I fixed it by deleting the folder from my plugin directory. 

Sorry to bother you.  SMDH.. LOL
