### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by graymon32** [Leanny/PKHeX_Raid_Plugin#66]
so on my shield save when I click display raids, I get the error bellow? Any advice?

Exception Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PKHeX_Raid_Plugin.RaidManager.InitializeDenList(RaidSpawnList8 raids, RaidSpawnList8 raidsArmor, RaidSpawnList8 raidsCrown)
   at PKHeX_Raid_Plugin.RaidManager..ctor(SaveBlockAccessor8SWSH blocks, GameVersion game, Int32 badges, UInt32 tid, UInt32 sid)
   at PKHeX_Raid_Plugin.RaidList..ctor(SaveBlockAccessor8SWSH blocks, GameVersion game, Int32 badges, Int32 tid, Int32 sid)
   at PKHeX_Raid_Plugin.RaidPlugin.Open()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

PKHeX, Version=20.11.28.0, Culture=neutral, PublicKeyToken=null
C:\Users\Blood\Desktop\newest pkhex\pkhex\PKHeX (20.06.22)\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

AutoModPlugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Blood\Desktop\newest pkhex\pkhex\PKHeX (20.06.22)\plugins\AutoModPlugins.dll

DynamaxAdventureReset, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Blood\Desktop\newest pkhex\pkhex\PKHeX (20.06.22)\plugins\DynamaxAdventureReset.dll

PKHeX_Raid_Plugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Blood\Desktop\newest pkhex\pkhex\PKHeX (20.06.22)\plugins\PKHeX_Raid_Plugin.dll

QRPlugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Blood\Desktop\newest pkhex\pkhex\PKHeX (20.06.22)\plugins\QRPlugins.dll

PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll

WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

**Comment by Leanny** [comment]
Hi. Please update your pkhex. You are using  version from June. Also make sure that your savegame is updated. If you have an older version of a savegame, please use a release that was pre-dlc2

**Comment by graymon32** [comment]
its just the folder name I had the newest pkhex version, but it was the save that needed to be updated on my switch!! ty so much!!! I thought I did it but guess I didnt!!
