### ISSUE TITLE
I am getting the following error when displaying raids

### ISSUE THREAD

**Issue by hectorrshr** [Leanny/PKHeX_Raid_Plugin#9]
Exception Details:
System.MissingMethodException: Method not found: 'Byte PKHeX.Core.RaidSpawnDetail.get_Stars()'.
   at PKHeX_Raid_Plugin.DenManager..ctor(RaidSpawnList8 raids, GameVersion game, Int32 badges, UInt32 tid, UInt32 sid)
   at PKHeX_Raid_Plugin.Form1..ctor(RaidSpawnList8 raids, GameVersion game, Int32 badges, Int32 tid, Int32 sid)
   at PKHeX_Raid_Plugin.RaidPlugin.Open(SaveFile sav)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

PKHeX, Version=19.11.25.0, Culture=neutral, PublicKeyToken=null
C:\Users\hecto\Desktop\PKHeX (191125)b\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

PKHeX_Raid_Plugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\hecto\Desktop\PKHeX (191125)b\plugins\PKHeX_Raid_Plugin.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

**Comment by Leanny** [comment]
Please upgrade your PKHeX version

**Comment by hectorrshr** [comment]
Just did and this fixed my issue!
Thanks.
